### ISSUE TITLE
Client Crash Report: Error: Unable to preload CSS for /assets/RevoltApp.70d6a674.css

### ISSUE THREAD

**Issue by PrynsTag** [ggtylerr/divolt-desktop#11]
As you can see below, the divolt desktop is showing this error. Not sure if its related but before the `v1.0.6-d1.1.0` release, the web works and only the desktop and android app is the only client that is not working. After the release the web does not worked also and the desktop app is still not working.

![image](https://user-images.githubusercontent.com/56314705/194811335-13b678fa-2e42-465b-8887-a8eb3f96bfea.png)

**Comment by kpcenti** [comment]
Getting the same error also

**Comment by pmod25** [comment]
Any solution? I have the same problem

**Comment by SourceNatsu** [comment]
Use the web client and clear cache for https://divolt.xyz in your browser settings.

**Comment by ggtylerr** [comment]
> Not sure if its related but before the `v1.0.6-d1.1.0` release...

This issue was present before the release and was an attempt to see if the new update fixed it.

Apparently, the frontend was updated and changed the CSS file (the one shown in the error does not exist - I believe it's based on commit hash.) The problem is that the cache is not updated beforehand, and it tries to preload the old CSS file, hence the error.

I'm gonna try to make a bandage fix that will let you clear the cache from the tray icon. The, uh... one that's still invisible on Mac and Windows. And probably Linux. 

Reinstalling should also do the trick.

I'd also like to apologize for getting to this so late - Been busy with a full-time job and didn't get any notifications again.

If you happen to be in the FMHY server, feel free to ping / message me.

**Comment by ggtylerr** [comment]
Partly fixed with [`v1.0.6-d1.2.0`](https://github.com/ggtylerr/divolt-desktop/releases/tag/v1.0.6-d1.2.0) - Right click the tray icon and click "Clear Cache".

**Comment by SourceNatsu** [comment]
Fixed, I didn't even need to clear the cache as you instructed. I just opened Divolt Desktop.

**Comment by pedernal** [comment]
I got the same crash and error, simply reinstalling the application didn't solve it for me, for anyone in the same boat, make sure to also delete the directory that's left behind that has the Revolt's config files wherever they're stored in your system (for me it as at ~/.var/app/), then try reinstalling
